"""empty message

Revision ID: acc1d2d2622a
Revises: 
Create Date: 2018-05-25 15:24:05.513965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acc1d2d2622a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeker', sa.Column('work_year', sa.Integer(), nullable=True))
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('seeker', 'work_year')
    # ### end Alembic commands ###
